defaults:
  - default
  - model: null
  - override data: libero_90
  - _self_

experiment_name: "${hydra:runtime.choices.data}"
version: "${hydra:runtime.choices.model}/eval_ep${epoch}"
exp_log_dir: ${log_dir}/${experiment_name}/${version}
checkpoint_dir: ${exp_log_dir}/checkpoints

stage: test

trainer:
  limit_val_batches: 1

data:
  eval_config:
    enabled: true
    num_episodes_per_task: 20
    num_parallel: 20
